backend:
  name: test-repo

local_backend: true
media_folder: static/files
public_folder: /files

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
            - label: "Main"
              name: "main"
              widget: "object"
              collapsed: true
              fields:   
                - { label: Title, name: title, widget: string }
                - { label: Subheading, name: subheading, widget: string }
                - { label: Intro, name: intro, widget: markdown }
