backend:
  name: git-gateway
  branch: master

local_backend: true
media_folder: static/files
public_folder: /files

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"\\\
        fields:
          - { label: Title, name: title, widget: string }
